"""
Export Service - Export responses to various formats (PDF, Word, Markdown)
Phase 3 Feature #20
"""

from typing import Dict, Any, Optional
import logging
from datetime import datetime
import re
from io import BytesIO
from reportlab.lib.units import inch

from reportlab.platypus import Paragraph
from reportlab.lib.styles import getSampleStyleSheet

styles = getSampleStyleSheet()

logger = logging.getLogger(__name__)


class ExportService:
    """
    Service for exporting chat responses to various formats.
    Supports PDF, Word (DOCX), and Markdown exports.
    """
    
    def __init__(self):
        self.supported_formats = ['pdf', 'docx', 'markdown', 'md']

    def _wrap_table_cells(self, table_data):  # Fix 1: added missing `self`
        wrapped = []
        for row in table_data:
            wrapped_row = []
            for cell in row:
                if not cell:
                    cell = ""
                wrapped_row.append(Paragraph(str(cell), styles["Normal"]))
            wrapped.append(wrapped_row)
        return wrapped

    def _parse_markdown_table(self, text):
        """
        Convert markdown table into ReportLab table data
        """
        lines = [l.strip() for l in text.split("\n") if l.strip()]

        if len(lines) < 2:
            return None

        # remove separator row (|----|)
        header = lines[0]
        rows = lines[2:]

        header_cells = [c.strip() for c in header.split("|") if c.strip()]
        table_data = [header_cells]

        for row in rows:
            cells = [c.strip() for c in row.split("|") if c.strip()]
            if cells:
                table_data.append(cells)

        return table_data
    
    def export_to_markdown(
        self,
        query: str,
        response: str,
        citations: list,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Export response to Markdown format
        
        Args:
            query: User's query
            response: AI response text
            citations: List of citation dicts
            metadata: Optional metadata (intent, confidence, etc.)
            
        Returns:
            Markdown formatted string
        """
        try:
            # Build markdown document
            md_parts = []
            
            # Header
            md_parts.append("# MedResearch AI Response")
            md_parts.append(f"\n**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            
            # Query
            md_parts.append("## Query")
            md_parts.append(f"\n{query}\n")
            
            # Metadata (if provided)
            if metadata:
                md_parts.append("## Metadata")
                if 'intent' in metadata:
                    md_parts.append(f"- **Intent**: {metadata['intent']}")
                if 'confidence' in metadata:
                    md_parts.append(f"- **Confidence**: {metadata['confidence']:.2%}")
                if 'model' in metadata:
                    md_parts.append(f"- **Model**: {metadata['model']}")
                if 'processing_time_ms' in metadata:
                    md_parts.append(f"- **Processing Time**: {metadata['processing_time_ms']}ms")
                md_parts.append("")
            
            # Response
            md_parts.append("## Response")
            md_parts.append(f"\n{response}\n")
            
            # Citations
            if citations:
                md_parts.append("## Sources")
                md_parts.append("")
                for citation in citations:
                    num = citation.get('number', '?')
                    title = citation.get('title', 'Untitled')
                    source_type = citation.get('source_type', 'unknown')
                    source_id = citation.get('source_id', '')
                    url = citation.get('url', '')
                    relevance = citation.get('relevance_score', 0.0)
                    
                    md_parts.append(f"### [{num}] {title}")
                    md_parts.append(f"- **Type**: {source_type.upper()}")
                    if source_id:
                        md_parts.append(f"- **ID**: {source_id}")
                    if url:
                        md_parts.append(f"- **URL**: {url}")
                    md_parts.append(f"- **Relevance**: {relevance:.2%}")
                    md_parts.append("")
            
            # Footer
            md_parts.append("---")
            md_parts.append("*Generated by MedResearch AI*")
            
            markdown_content = "\n".join(md_parts)
            logger.info("Generated Markdown export")
            return markdown_content
            
        except Exception as e:
            logger.error(f"Markdown export error: {e}")
            raise
    
    def export_to_pdf(
        self,
        query: str,
        response: str,
        citations: list,
        metadata: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Export response to PDF format
        
        Args:
            query: User's query
            response: AI response text
            citations: List of citation dicts
            metadata: Optional metadata
            
        Returns:
            PDF file as bytes
        """
        try:
            # Try to import reportlab for PDF generation
            try:
                from reportlab.lib.pagesizes import letter
                from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
                from reportlab.lib.units import inch
                from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
                from reportlab.lib import colors
                from reportlab.lib.enums import TA_LEFT, TA_CENTER
            except ImportError:
                logger.warning("reportlab not installed, falling back to markdown")
                # Fallback to markdown if reportlab not available
                markdown = self.export_to_markdown(query, response, citations, metadata)
                return markdown.encode('utf-8')
            
            # Create PDF buffer
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            story = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1a73e8'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=colors.HexColor('#1a73e8'),
                spaceAfter=12,
                spaceBefore=12
            )
            
            # Title
            story.append(Paragraph("MedResearch AI Response", title_style))
            story.append(Spacer(1, 0.2*inch))
            
            # Date
            date_text = f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            story.append(Paragraph(date_text, styles['Normal']))
            story.append(Spacer(1, 0.3*inch))
            
            # Query
            story.append(Paragraph("Query", heading_style))
            query_text = query.replace('<', '&lt;').replace('>', '&gt;')
            story.append(Paragraph(query_text, styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
            
            # Metadata
            if metadata:
                story.append(Paragraph("Metadata", heading_style))
                meta_data = []
                if 'intent' in metadata:
                    meta_data.append(['Intent:', metadata['intent']])
                if 'confidence' in metadata:
                    confidence = metadata.get("confidence")
                    if confidence is not None:
                        meta_data.append(['Confidence:', f"{confidence:.2%}"])
                if 'model' in metadata:
                    meta_data.append(['Model:', metadata['model']])
                if 'processing_time_ms' in metadata:
                    meta_data.append(['Processing Time:', f"{metadata['processing_time_ms']}ms"])
                
                if meta_data:
                    meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
                    meta_table.setStyle(TableStyle([
                        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
                        ('FONTSIZE', (0, 0), (-1, -1), 10),
                        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ]))
                    story.append(meta_table)
                    story.append(Spacer(1, 0.2*inch))
            
            # Response
            story.append(Paragraph("Response", heading_style))

            # Define heading styles for #, ##, ###
            h1_style = ParagraphStyle(
                'MDHeading1', parent=styles['Heading1'],
                fontSize=18, textColor=colors.HexColor('#1a73e8'),
                spaceBefore=14, spaceAfter=6
            )
            h2_style = ParagraphStyle(
                'MDHeading2', parent=styles['Heading2'],
                fontSize=15, textColor=colors.HexColor('#1a73e8'),
                spaceBefore=12, spaceAfter=5
            )
            h3_style = ParagraphStyle(
                'MDHeading3', parent=styles['Heading3'],
                fontSize=13, textColor=colors.HexColor('#333333'),
                spaceBefore=10, spaceAfter=4
            )
            bullet_style = ParagraphStyle(
                'MDBullet', parent=styles['Normal'],
                leftIndent=20, firstLineIndent=0,
                spaceBefore=2, spaceAfter=2
            )

            def inline_format(text):
                """Apply inline markdown: escape HTML, then bold/italic."""
                text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                # bold+italic ***text***
                text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<b><i>\1</i></b>', text)
                # bold **text**
                text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
                # italic *text*
                text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
                # inline code `text`
                text = re.sub(r'`(.+?)`', r'<font name="Courier">\1</font>', text)
                return text

            # Collect lines and group table blocks, then render line-by-line
            lines = response.split("\n")
            i = 0
            while i < len(lines):
                line = lines[i]

                # --- Markdown table: collect all consecutive table lines ---
                if line.strip().startswith("|") and "|" in line:
                    table_lines = []
                    while i < len(lines) and lines[i].strip().startswith("|"):
                        table_lines.append(lines[i])
                        i += 1
                    table_block = "\n".join(table_lines)
                    table_data = self._parse_markdown_table(table_block)
                    if table_data:
                        table_data = self._wrap_table_cells(table_data)
                        col_count = len(table_data[0])
                        usable_width = 6.5 * inch
                        col_widths = [usable_width / col_count] * col_count
                        table = Table(table_data, colWidths=col_widths, repeatRows=1)
                        table.setStyle(TableStyle([
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("VALIGN", (0, 0), (-1, -1), "TOP"),
                            ("LEFTPADDING", (0, 0), (-1, -1), 6),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                            ("TOPPADDING", (0, 0), (-1, -1), 4),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ]))
                        story.append(table)
                        story.append(Spacer(1, 0.2 * inch))
                    continue

                stripped = line.strip()

                # --- Headings: #, ##, ### ---
                heading_match = re.match(r'^(#{1,6})\s+(.*)', stripped)
                if heading_match:
                    level = len(heading_match.group(1))
                    text = inline_format(heading_match.group(2))
                    style = h1_style if level == 1 else h2_style if level == 2 else h3_style
                    story.append(Paragraph(text, style))
                    i += 1
                    continue

                # --- Bullet points: - or * ---
                bullet_match = re.match(r'^[-*]\s+(.*)', stripped)
                if bullet_match:
                    text = inline_format(bullet_match.group(1))
                    story.append(Paragraph(f"• {text}", bullet_style))
                    i += 1
                    continue

                # --- Numbered list: 1. 2. etc ---
                num_match = re.match(r'^(\d+)\.\s+(.*)', stripped)
                if num_match:
                    num = num_match.group(1)
                    text = inline_format(num_match.group(2))
                    story.append(Paragraph(f"{num}. {text}", bullet_style))
                    i += 1
                    continue

                # --- Horizontal rule ---
                if re.match(r'^[-*_]{3,}$', stripped):
                    story.append(Spacer(1, 0.1 * inch))
                    i += 1
                    continue

                # --- Blank line ---
                if not stripped:
                    story.append(Spacer(1, 0.08 * inch))
                    i += 1
                    continue

                # --- Normal paragraph line ---
                story.append(Paragraph(inline_format(stripped), styles['Normal']))
                story.append(Spacer(1, 0.05 * inch))
                i += 1
            
            # Citations
            if citations:
                story.append(Spacer(1, 0.2*inch))
                story.append(Paragraph("Sources", heading_style))
                
                for citation in citations:
                    num = citation.get('number', '?')
                    title = citation.get('title', 'Untitled')
                    source_type = citation.get('source_type', 'unknown')
                    source_id = citation.get('source_id', '')
                    url = citation.get('url', '')
                    
                    citation_text = f"<b>[{num}]</b> {title}"
                    story.append(Paragraph(citation_text, styles['Normal']))
                    
                    details = f"Type: {source_type.upper()}"
                    if source_id:
                        details += f" | ID: {source_id}"
                    if url:
                        details += f" | URL: {url}"
                    
                    story.append(Paragraph(details, styles['Normal']))
                    story.append(Spacer(1, 0.1*inch))
            
            # Footer
            story.append(Spacer(1, 0.3*inch))
            footer_text = "<i>Generated by MedResearch AI</i>"
            story.append(Paragraph(footer_text, styles['Normal']))
            
            # Build PDF
            doc.build(story)
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info("Generated PDF export")
            return pdf_bytes
            
        except Exception as e:
            logger.error(f"PDF export error: {e}")
            raise
    
    def export_to_docx(
        self,
        query: str,
        response: str,
        citations: list,
        metadata: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Export response to Word (DOCX) format
        
        Args:
            query: User's query
            response: AI response text
            citations: List of citation dicts
            metadata: Optional metadata
            
        Returns:
            DOCX file as bytes
        """
        try:
            # Try to import python-docx
            try:
                from docx import Document
                from docx.shared import Inches, Pt, RGBColor
                from docx.enum.text import WD_ALIGN_PARAGRAPH
            except ImportError:
                logger.warning("python-docx not installed, falling back to markdown")
                # Fallback to markdown if python-docx not available
                markdown = self.export_to_markdown(query, response, citations, metadata)
                return markdown.encode('utf-8')
            
            # Create document
            doc = Document()
            
            # Title
            title = doc.add_heading('MedResearch AI Response', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Date
            date_para = doc.add_paragraph()
            date_para.add_run(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            doc.add_paragraph()
            
            # Query
            doc.add_heading('Query', level=1)
            doc.add_paragraph(query)
            
            # Metadata
            if metadata:
                doc.add_heading('Metadata', level=1)
                if 'intent' in metadata:
                    p = doc.add_paragraph()
                    p.add_run('Intent: ').bold = True
                    p.add_run(metadata['intent'])
                if 'confidence' in metadata:
                    p = doc.add_paragraph()
                    p.add_run('Confidence: ').bold = True
                    p.add_run(f"{metadata['confidence']:.2%}")
                if 'model' in metadata:
                    p = doc.add_paragraph()
                    p.add_run('Model: ').bold = True
                    p.add_run(metadata['model'])
                if 'processing_time_ms' in metadata:
                    p = doc.add_paragraph()
                    p.add_run('Processing Time: ').bold = True
                    p.add_run(f"{metadata['processing_time_ms']}ms")
                doc.add_paragraph()
            
            # Response
            doc.add_heading('Response', level=1)
            # Split response into paragraphs and add
            for para in response.split('\n\n'):
                if para.strip():
                    # Check if it's a header (starts with ##)
                    if para.strip().startswith('##'):
                        header_text = para.strip().replace('##', '').strip()
                        doc.add_heading(header_text, level=2)
                    else:
                        doc.add_paragraph(para.strip())
            
            # Citations
            if citations:
                doc.add_page_break()
                doc.add_heading('Sources', level=1)
                
                for citation in citations:
                    num = citation.get('number', '?')
                    title = citation.get('title', 'Untitled')
                    source_type = citation.get('source_type', 'unknown')
                    source_id = citation.get('source_id', '')
                    url = citation.get('url', '')
                    relevance = citation.get('relevance_score', 0.0)
                    
                    # Citation heading
                    p = doc.add_paragraph()
                    p.add_run(f"[{num}] {title}").bold = True
                    
                    # Citation details
                    details = doc.add_paragraph(style='List Bullet')
                    details.add_run(f"Type: {source_type.upper()}")
                    
                    if source_id:
                        details = doc.add_paragraph(style='List Bullet')
                        details.add_run(f"ID: {source_id}")
                    
                    if url:
                        details = doc.add_paragraph(style='List Bullet')
                        details.add_run(f"URL: {url}")
                    
                    details = doc.add_paragraph(style='List Bullet')
                    details.add_run(f"Relevance: {relevance:.2%}")
                    
                    doc.add_paragraph()
            
            # Footer
            footer_para = doc.add_paragraph()
            footer_run = footer_para.add_run('Generated by MedResearch AI')
            footer_run.italic = True
            footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Save to buffer
            buffer = BytesIO()
            doc.save(buffer)
            docx_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info("Generated DOCX export")
            return docx_bytes
            
        except Exception as e:
            logger.error(f"DOCX export error: {e}")
            raise
    
    def export(
        self,
        format: str,
        query: str,
        response: str,
        citations: list,
        metadata: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Export response to specified format
        
        Args:
            format: Export format ('pdf', 'docx', 'markdown', 'md')
            query: User's query
            response: AI response text
            citations: List of citation dicts
            metadata: Optional metadata
            
        Returns:
            Exported file as bytes
        """
        format_lower = format.lower()
        
        if format_lower not in self.supported_formats:
            raise ValueError(f"Unsupported format: {format}. Supported: {self.supported_formats}")
        
        if format_lower in ['markdown', 'md']:
            content = self.export_to_markdown(query, response, citations, metadata)
            return content.encode('utf-8')
        elif format_lower == 'pdf':
            return self.export_to_pdf(query, response, citations, metadata)
        elif format_lower == 'docx':
            return self.export_to_docx(query, response, citations, metadata)
        else:
            raise ValueError(f"Unsupported format: {format}")


# Singleton instance
_export_service = None


def get_export_service() -> ExportService:
    """Get or create the export service singleton"""
    global _export_service
    if _export_service is None:
        _export_service = ExportService()
    return _export_service