name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        run: |
          echo "REPO=${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          docker build -t $REPO:${{ github.sha }} -f backend/Dockerfile backend
          docker tag $REPO:${{ github.sha }} $IMAGE_URI
          docker push $IMAGE_URI

      - name: Print image name
        run: |
          echo "Final image:"
          echo $IMAGE_URI
